### PR TITLE
Some new update

### PR DESCRIPTION
**Pull request by nick2781**
Hi, I've updated the repo to header-only and single header file.

Make it easier to use.

I've tested it in Linux(CentOS7) and Windows10(VS2019).

### CODE REVIEW

**Comment by chinuno-usami** [comment]
Could you tell me details about changes you made?
It seems you add a `HealthCheck` api to check status of service.
And put all of codes into a single header file.

In my opinion. Header only design for a SDK is not good.
It requires to be compiled evey time you use the SDK. Usually, a SDK api would be used in serval of cpp files.
Besides, it requires to recompile your program when SDK update if use header only design.
It's fatal when you need to update (or such as fix some bug) the SDK at production environment.
That's why I use pimpl technique.

Putting all of source code into one file also not beneficial for maintenance of project. 
Usually, single header only project developed in a set of individual headers.
And published by generating a single file merged from individual headers.
Such as [catch2](https://github.com/catchorg/Catch2/) publish in this way.

Do not use `aux_source_directory` in `CMakeLists.txt`. Reason at [here](https://cmake.org/cmake/help/latest/command/aux_source_directory.html)

**Comment by nick2781** [comment]
I list the details What I changed.

- Change all code into one header file
- Add `HealthCheck` function _I used it in my project._
- Add the test of `HealthCheck`
- Support `Windows`

The reason I put all code into one file is I have to link many libraries when my projects have many 3rd party dependencies. Now many libraries use header-only way to omit the compilation process, make easier for beginners.

I'll change `aux_source_directory`.

**Comment by chinuno-usami** [comment]
`HealthCheck` and Support Windows is good. 
But I wish you can 
1. Follow original naming convention.
2. Not to use single header-only design.

I will merge your PR if you modify your PR as listed.

If you worry about dependencies.
You can use this project as a sub project.
1. Compile as a static library. It would not produce any runtime dynamic library dependencies.
2. Just use it as part of your project. All you need is to add cpps into your source file list. Not need to compile individually as 3rd library.

**Comment by nick2781** [comment]
OK, I'll change it to what you want later. I use it in my project first, thanks.

**Pull request closed without merging**
